[Anagrammes]
url="http://www.lexique.org/databases/_json/anagrammes.json"

[AoA32]
url="http://www.lexique.org/databases/_json/AoA-32lang.json"

[AoA_FamConcept_1225]
url="http://www.lexique.org/databases/_json/AoA_FamConcept_1225.json"

[AoA_FreqSub_1493]
url="http://www.lexique.org/databases/_json/AoA_FreqSub_1493.json"

[Imag_1493]
url="http://www.lexique.org/databases/_json/Imag_1493.json"

[Lexique3]
url="http://www.lexique.org/databases/_json/Lexique383.json"

[Megalex_auditory]
url="http://www.lexique.org/databases/_json/Megalex-auditory.json"

[Megalex_visual]
url="http://www.lexique.org/databases/_json/Megalex-visual.json"

[SemantiQc_auditory]
url="http://www.lexique.org/databases/_json/SemantiQc_auditory.json"

[SemantiQc_familiarity_concept]
url="http://www.lexique.org/databases/_json/SemantiQc_familiarity_concept.json"

[SemantiQc_visual]
url="http://www.lexique.org/databases/_json/SemantiQc_visual.json"

[SensoryExp_1659]
url="http://www.lexique.org/databases/_json/SensoryExp_1659.json"

[SubtlexUS]
url="http://www.lexique.org/databases/_json/SUBTLEX-US.json"

[Valemo_Adultes_604]
url="http://www.lexique.org/databases/_json/Valemo_Adultes_604.json"

[ValEmo_Arous_1286]
url="http://www.lexique.org/databases/_json/ValEmo_Arous_1286.json"

[ValEmo_Arous_Imag_835]
url="http://www.lexique.org/databases/_json/ValEmo_Arous_Imag_835.json"

[Valemo_Enfants_600]
url="http://www.lexique.org/databases/_json/Valemo_Enfants_600.json"

[Voisins]
url="http://www.lexique.org/databases/_json/Voisins.json"

[WorldLex_EN]
url="http://www.lexique.org/databases/_json/WorldLex-English.json"

[WorldLex_FR]
url="http://www.lexique.org/databases/_json/WorldLex-French.json"

[WorldLex_AF]
url="http://www.lexique.org/databases/_json/WorldLex-Afrikaans.json"

[WorldLex_ALB]
url="http://www.lexique.org/databases/_json/WorldLex-Albanian.json"

[WorldLex_AMH]
url="http://www.lexique.org/databases/_json/WorldLex-Amharic.json"

[WorldLex_ARA]
url="http://www.lexique.org/databases/_json/WorldLex-Arabic.json"

[WorldLex_ARM]
url="http://www.lexique.org/databases/_json/WorldLex-Armenian.json"

[WorldLex_AZE]
url="http://www.lexique.org/databases/_json/WorldLex-Azeri.json"

[WorldLex_BEN]
url="http://www.lexique.org/databases/_json/WorldLex-Bengali.json"

[WorldLex_BOS]
url="http://www.lexique.org/databases/_json/WorldLex-Bosnian.json"

[WorldLex_CAT]
url="http://www.lexique.org/databases/_json/WorldLex-Catalan.json"

[WorldLex_CHI]
url="http://www.lexique.org/databases/_json/WorldLex-Chinese-Simplified.json"

[WorldLex_CRO]
url="http://www.lexique.org/databases/_json/WorldLex-Croatian.json"

[WorldLex_CZE]
url="http://www.lexique.org/databases/_json/WorldLex-Czech.json"

[WorldLex_DK]
url="http://www.lexique.org/databases/_json/WorldLex-Danish.json"

[WorldLex_NL]
url="http://www.lexique.org/databases/_json/WorldLex-Dutch.json"

[WorldLex_EST]
url="http://www.lexique.org/databases/_json/WorldLex-Estonian.json"

[WorldLex_FI]
url="http://www.lexique.org/databases/_json/WorldLex-Finnish.json"

[WorldLex_GE]
url="http://www.lexique.org/databases/_json/WorldLex-Georgian.json"

[WorldLex_DE]
url="http://www.lexique.org/databases/_json/WorldLex-German.json"

[WorldLex_GRE]
url="http://www.lexique.org/databases/_json/WorldLex-Greek.json"

[WorldLex_GL]
url="http://www.lexique.org/databases/_json/WorldLex-Greenlandic.json"

[WorldLex_GU]
url="http://www.lexique.org/databases/_json/WorldLex-Gujarati.json"

[WorldLex_HE]
url="http://www.lexique.org/databases/_json/WorldLex-Hebrew.json"

[WorldLex_HI]
url="http://www.lexique.org/databases/_json/WorldLex-Hindi.json"

[WorldLex_HU]
url="http://www.lexique.org/databases/_json/WorldLex-Hungarian.json"

[WorldLex_ICE]
url="http://www.lexique.org/databases/_json/WorldLex-Icelandic.json"

[WorldLex_ID]
url="http://www.lexique.org/databases/_json/WorldLex-Indonesian.json"

[WorldLex_ITA]
url="http://www.lexique.org/databases/_json/WorldLex-Italian.json"

[WorldLex_JAP]
url="http://www.lexique.org/databases/_json/WorldLex-Japanese.json"

[WorldLex_KN]
url="http://www.lexique.org/databases/_json/WorldLex-Kannada.json"

[WorldLex_KZ]
url="http://www.lexique.org/databases/_json/WorldLex-Kazakh.json"

[WorldLex_KHM]
url="http://www.lexique.org/databases/_json/WorldLex-Khmer.json"

[WorldLex_KR]
url="http://www.lexique.org/databases/_json/WorldLex-Korean.json"

[WorldLex_LV]
url="http://www.lexique.org/databases/_json/WorldLex-Latvian.json"

[WorldLex_LIT]
url="http://www.lexique.org/databases/_json/WorldLex-Lithuanian.json"

[WorldLex_MK]
url="http://www.lexique.org/databases/_json/WorldLex-Macedonian.json"

[WorldLex_ML]
url="http://www.lexique.org/databases/_json/WorldLex-Malayalam.json"

[WorldLex_MY]
url="http://www.lexique.org/databases/_json/WorldLex-Malaysian.json"

[WorldLex_MN]
url="http://www.lexique.org/databases/_json/WorldLex-Mongolian.json"

[WorldLex_NEP]
url="http://www.lexique.org/databases/_json/WorldLex-Nepali.json"

[WorldLex_NOB]
url="http://www.lexique.org/databases/_json/WorldLex-Norwegian.json"

[WorldLex_PER]
url="http://www.lexique.org/databases/_json/WorldLex-Persian.json"

[WorldLex_PL]
url="http://www.lexique.org/databases/_json/WorldLex-Polish.json"

[WorldLex_POR_BR]
url="http://www.lexique.org/databases/_json/WorldLex-Portuguese-Brazil.json"

[WorldLex_POR_EU]
url="http://www.lexique.org/databases/_json/WorldLex-Portuguese-Europe.json"

[WorldLex_PAN]
url="http://www.lexique.org/databases/_json/WorldLex-Punjabi.json"

[WorldLex_RO]
url="http://www.lexique.org/databases/_json/WorldLex-Romanian.json"

[WorldLex_RU]
url="http://www.lexique.org/databases/_json/WorldLex-Russian.json"

[WorldLex_SER]
url="http://www.lexique.org/databases/_json/WorldLex-Serbian.json"

[WorldLex_SIN]
url="http://www.lexique.org/databases/_json/WorldLex-Sinhala.json"

[WorldLex_SK]
url="http://www.lexique.org/databases/_json/WorldLex-Slovak.json"

[WorldLex_SL]
url="http://www.lexique.org/databases/_json/WorldLex-Slovenian.json"

[WorldLex_ES_SA]
url="http://www.lexique.org/databases/_json/WorldLex-Spanish-Latin-America.json"

[WorldLex_ES]
url="http://www.lexique.org/databases/_json/WorldLex-Spanish-Spain.json"

[WorldLex_SWA]
url="http://www.lexique.org/databases/_json/WorldLex-Swahili.json"

[WorldLex_SWE]
url="http://www.lexique.org/databases/_json/WorldLex-Swedish.json"

[WorldLex_TGL]
url="http://www.lexique.org/databases/_json/WorldLex-Tagalog.json"

[WorldLex_TA]
url="http://www.lexique.org/databases/_json/WorldLex-Tamil.json"

[WorldLex_TEL]
url="http://www.lexique.org/databases/_json/WorldLex-Telugu.json"

[WorldLex_TUR]
url="http://www.lexique.org/databases/_json/WorldLex-Turkish.json"

[WorldLex_UK]
url="http://www.lexique.org/databases/_json/WorldLex-Ukrainian.json"

[WorldLex_URD]
url="http://www.lexique.org/databases/_json/WorldLex-Urdu.json"

[WorldLex_UZ]
url="http://www.lexique.org/databases/_json/WorldLex-Uzbek.json"

[WorldLex_VIE]
url="http://www.lexique.org/databases/_json/WorldLex-Vietnamese.json"

[WorldLex_CY]
url="http://www.lexique.org/databases/_json/WorldLex-Welsh.json"
