[Anagrammes]
# url="http://www.lexique.org/databases/_json/anagrammes.json"
url="../../datasets-info/anagrammes.json"

[AoA32]
url="http://www.lexique.org/databases/_json/AoA-32lang.json"

[AoA_FamConcept_1225]
url="http://www.lexique.org/databases/_json/AoA_FamConcept_1225.json"

[AoA_FreqSub_1493]
url="http://www.lexique.org/databases/_json/AoA_FreqSub_1493.json"

# Imag_1493=c("http://www.lexique.org/databases/_json/Imag_1493.json", "Imag_1493.rds"),
# Lexique3=c("http://www.lexique.org/databases/_json/Lexique383.json", "Lexique383.rds"),
# Megalex_auditory=c("http://www.lexique.org/databases/_json/Megalex-auditory.json", "Megalex-auditory.rds"),
# Megalex_visual=c("http://www.lexique.org/databases/_json/Megalex-visual.json", "Megalex-visual.rds"),
# SemantiQc_auditory=c("http://www.lexique.org/databases/_json/SemantiQc_auditory.json", "SemantiQc_auditory.rds"),
# SemantiQc_familiarity_concept=c("http://www.lexique.org/databases/_json/SemantiQc_familiarity_concept.json", "SemantiQc_familiarity_concept.rds"),
# SemantiQc_visual=c("http://www.lexique.org/databases/_json/SemantiQc_visual.json", "SemantiQc_visual.rds"),
# SensoryExp_1659=c("http://www.lexique.org/databases/_json/SensoryExp_1659.json", "SensoryExp_1659.rds"),
# SubtlexUS=c("http://www.lexique.org/databases/_json/SUBTLEX-US.json", "SUBTLEXus.rds"),
# Valemo_Adultes_604=c("http://www.lexique.org/databases/_json/Valemo_Adultes_604.json", "Valemo_Adultes_604.rds"),
# ValEmo_Arous_1286=c("http://www.lexique.org/databases/_json/ValEmo_Arous_1286.json", "ValEmo_Arous_1286.rds"),
# ValEmo_Arous_Imag_835=c("http://www.lexique.org/databases/_json/ValEmo_Arous_Imag_835.json", "ValEmo_Arous_Imag_835.rds"),
# Valemo_Enfants_600=c("http://www.lexique.org/databases/_json/Valemo_Enfants_600.json", "Valemo_Enfants_600.rds"),
# Voisins=c("http://www.lexique.org/databases/_json/Voisins.json", "Voisins.rds"),
# WorldLex_EN=c("http://www.lexique.org/databases/_json/WorldLex-English.json", "WorldLex_EN.rds"),
# WorldLex_FR=c("http://www.lexique.org/databases/_json/WorldLex-French.json", "WorldLex_FR.rds"),
# WorldLex_AF=c("http://www.lexique.org/databases/_json/WorldLex-Afrikaans.json", "WorldLex-Afrikaans.rds"),
# WorldLex_ALB=c("http://www.lexique.org/databases/_json/WorldLex-Albanian.json", "WorldLex-Albanian.rds"),
# WorldLex_AMH=c("http://www.lexique.org/databases/_json/WorldLex-Amharic.json", "WorldLex-Amharic.rds"),
# WorldLex_ARA=c("http://www.lexique.org/databases/_json/WorldLex-Arabic.json", "WorldLex-Arabic.rds"),
# WorldLex_ARM=c("http://www.lexique.org/databases/_json/WorldLex-Armenian.json", "WorldLex-Armenian.rds"),
# WorldLex_AZE=c("http://www.lexique.org/databases/_json/WorldLex-Azeri.json", "WorldLex-Azeri.rds"),
# WorldLex_BEN=c("http://www.lexique.org/databases/_json/WorldLex-Bengali.json", "WorldLex-Bengali.rds"),
# WorldLex_BOS=c("http://www.lexique.org/databases/_json/WorldLex-Bosnian.json", "WorldLex-Bosnian.rds"),
# WorldLex_CAT=c("http://www.lexique.org/databases/_json/WorldLex-Catalan.json", "WorldLex-Catalan.rds"),
# WorldLex_CHI=c("http://www.lexique.org/databases/_json/WorldLex-Chinese-Simplified.json", "WorldLex-Chinese-Simplified.rds"),
# WorldLex_CRO=c("http://www.lexique.org/databases/_json/WorldLex-Croatian.json", "WorldLex-Croatian.rds"),
# WorldLex_CZE=c("http://www.lexique.org/databases/_json/WorldLex-Czech.json", "WorldLex-Czech.rds"),
# WorldLex_DK=c("http://www.lexique.org/databases/_json/WorldLex-Danish.json", "WorldLex-Danish.rds"),
# WorldLex_NL=c("http://www.lexique.org/databases/_json/WorldLex-Dutch.json", "WorldLex-Dutch.rds"),
# WorldLex_EST=c("http://www.lexique.org/databases/_json/WorldLex-Estonian.json", "WorldLex-Estonian.rds"),
# WorldLex_FI=c("http://www.lexique.org/databases/_json/WorldLex-Finnish.json", "WorldLex-Finnish.rds"),
# WorldLex_GE=c("http://www.lexique.org/databases/_json/WorldLex-Georgian.json", "WorldLex-Georgian.rds"),
# WorldLex_DE=c("http://www.lexique.org/databases/_json/WorldLex-German.json", "WorldLex-German.rds"),
# WorldLex_GRE=c("http://www.lexique.org/databases/_json/WorldLex-Greek.json", "WorldLex-Greek.rds"),
# WorldLex_GL=c("http://www.lexique.org/databases/_json/WorldLex-Greenlandic.json", "WorldLex-Greenlandic.rds"),
# WorldLex_GU=c("http://www.lexique.org/databases/_json/WorldLex-Gujarati.json", "WorldLex-Gujarati.rds"),
# WorldLex_HE=c("http://www.lexique.org/databases/_json/WorldLex-Hebrew.json", "WorldLex-Hebrew.rds"),
# WorldLex_HI=c("http://www.lexique.org/databases/_json/WorldLex-Hindi.json", "WorldLex-Hindi.rds"),
# WorldLex_HU=c("http://www.lexique.org/databases/_json/WorldLex-Hungarian.json", "WorldLex-Hungarian.rds"),
# WorldLex_ICE=c("http://www.lexique.org/databases/_json/WorldLex-Icelandic.json", "WorldLex-Icelandic.rds"),
# WorldLex_ID=c("http://www.lexique.org/databases/_json/WorldLex-Indonesian.json", "WorldLex-Indonesian.rds"),
# WorldLex_ITA=c("http://www.lexique.org/databases/_json/WorldLex-Italian.json", "WorldLex-Italian.rds"),
# WorldLex_JAP=c("http://www.lexique.org/databases/_json/WorldLex-Japanese.json", "WorldLex-Japanese.rds"),
# WorldLex_KN=c("http://www.lexique.org/databases/_json/WorldLex-Kannada.json", "WorldLex-Kannada.rds"),
# WorldLex_KZ=c("http://www.lexique.org/databases/_json/WorldLex-Kazakh.json", "WorldLex-Kazakh.rds"),
# WorldLex_KHM=c("http://www.lexique.org/databases/_json/WorldLex-Khmer.json", "WorldLex-Khmer.rds"),
# WorldLex_KR=c("http://www.lexique.org/databases/_json/WorldLex-Korean.json", "WorldLex-Korean.rds"),
# WorldLex_LV=c("http://www.lexique.org/databases/_json/WorldLex-Latvian.json", "WorldLex-Latvian.rds"),
# WorldLex_LIT=c("http://www.lexique.org/databases/_json/WorldLex-Lithuanian.json", "WorldLex-Lithuanian.rds"),
# WorldLex_MK=c("http://www.lexique.org/databases/_json/WorldLex-Macedonian.json", "WorldLex-Macedonian.rds"),
# WorldLex_ML=c("http://www.lexique.org/databases/_json/WorldLex-Malayalam.json", "WorldLex-Malayalam.rds"),
# WorldLex_MY=c("http://www.lexique.org/databases/_json/WorldLex-Malaysian.json", "WorldLex-Malaysian.rds"),
# WorldLex_MN=c("http://www.lexique.org/databases/_json/WorldLex-Mongolian.json", "WorldLex-Mongolian.rds"),
# WorldLex_NEP=c("http://www.lexique.org/databases/_json/WorldLex-Nepali.json", "WorldLex-Nepali.rds"),
# WorldLex_NOB=c("http://www.lexique.org/databases/_json/WorldLex-Norwegian.json", "WorldLex-Norwegian.rds"),
# WorldLex_PER=c("http://www.lexique.org/databases/_json/WorldLex-Persian.json", "WorldLex-Persian.rds"),
# WorldLex_PL=c("http://www.lexique.org/databases/_json/WorldLex-Polish.json", "WorldLex-Polish.rds"),
# WorldLex_POR_BR=c("http://www.lexique.org/databases/_json/WorldLex-Portuguese-Brazil.json", "WorldLex-Portuguese-Brazil.rds"),
# WorldLex_POR_EU=c("http://www.lexique.org/databases/_json/WorldLex-Portuguese-Europe.json", "WorldLex-Portuguese-Europe.rds"),
# WorldLex_PAN=c("http://www.lexique.org/databases/_json/WorldLex-Punjabi.json", "WorldLex-Punjabi.rds"),
# WorldLex_RO=c("http://www.lexique.org/databases/_json/WorldLex-Romanian.json", "WorldLex-Romanian.rds"),
# WorldLex_RU=c("http://www.lexique.org/databases/_json/WorldLex-Russian.json", "WorldLex-Russian.rds"),
# WorldLex_SER=c("http://www.lexique.org/databases/_json/WorldLex-Serbian.json", "WorldLex-Serbian.rds"),
# WorldLex_SIN=c("http://www.lexique.org/databases/_json/WorldLex-Sinhala.json", "WorldLex-Sinhala.rds"),
# WorldLex_SK=c("http://www.lexique.org/databases/_json/WorldLex-Slovak.json", "WorldLex-Slovak.rds"),
# WorldLex_SL=c("http://www.lexique.org/databases/_json/WorldLex-Slovenian.json", "WorldLex-Slovenian.rds"),
# WorldLex_ES_SA=c("http://www.lexique.org/databases/_json/WorldLex-Spanish-Latin-America.json", "WorldLex-Spanish-Latin-America.rds"),
# WorldLex_ES=c("http://www.lexique.org/databases/_json/WorldLex-Spanish-Spain.json", "WorldLex-Spanish-Spain.rds"),
# WorldLex_SWA=c("http://www.lexique.org/databases/_json/WorldLex-Swahili.json", "WorldLex-Swahili.rds"),
# WorldLex_SWE=c("http://www.lexique.org/databases/_json/WorldLex-Swedish.json", "WorldLex-Swedish.rds"),
# WorldLex_TGL=c("http://www.lexique.org/databases/_json/WorldLex-Tagalog.json", "WorldLex-Tagalog.rds"),
# WorldLex_TA=c("http://www.lexique.org/databases/_json/WorldLex-Tamil.json", "WorldLex-Tamil.rds"),
# WorldLex_TEL=c("http://www.lexique.org/databases/_json/WorldLex-Telugu.json", "WorldLex-Telugu.rds"),
# WorldLex_TUR=c("http://www.lexique.org/databases/_json/WorldLex-Turkish.json", "WorldLex-Turkish.rds"),
# WorldLex_UK=c("http://www.lexique.org/databases/_json/WorldLex-Ukrainian.json", "WorldLex-Ukrainian.rds"),
# WorldLex_URD=c("http://www.lexique.org/databases/_json/WorldLex-Urdu.json", "WorldLex-Urdu.rds"),
# WorldLex_UZ=c("http://www.lexique.org/databases/_json/WorldLex-Uzbek.json", "WorldLex-Uzbek.rds"),
# WorldLex_VIE=c("http://www.lexique.org/databases/_json/WorldLex-Vietnamese.json", "WorldLex-Vietnamese.rds"),
# WorldLex_CY=c("http://www.lexique.org/databases/_json/WorldLex-Welsh.json", "WorldLex-Welsh.rds")
# )
